CREATE DATABASE marketdb;

CREATE USER 'admin'@'localhost' IDENTIFIED BY '123456';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, INDEX, DROP, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES ON marketdb.* TO 'admin'@'localhost';

USE marketdb;

CREATE TABLE tbl_markets
(
   ID INT NOT NULL AUTO_INCREMENT,
   NAME VARCHAR(100) NOT NULL,
   TYPE VARCHAR(100) NOT NULL,
   PRIMARY KEY (ID)
);

CREATE TABLE tbl_sections
(
   ID INT NOT NULL AUTO_INCREMENT,
   NAME VARCHAR(100) NOT NULL,
   TYPE VARCHAR(100) NOT NULL,
   PRIMARY KEY (ID)
);

CREATE TABLE tbl_employees
(
   ID INT NOT NULL AUTO_INCREMENT,
   FIRSTNAME VARCHAR(100) NOT NULL,
   LASTNAME VARCHAR(100) NOT NULL,
   BIRTHDATE VARCHAR(50) NOT NULL,
   SALARY DECIMAL(15, 2) NOT NULL,
   SECTION VARCHAR(100) NOT NULL,
   PRIMARY KEY (ID)
);